Testing - Replaced public List<T> findAll() with dummy code to see if it removes a previous exception. java.lang.IllegalStateException: Unable to retrieve EntityManagerFactory for unitName AffableBeanPU.
New exception is -

javax.servlet.ServletException: Servlet.init() for servlet ControllerServlet threw exception

root cause
javax.ejb.EJBAccessException

root cause
javax.ejb.AccessLocalException: Client not authorized for this invocation